### ISSUE TITLE
pthread_join() blocks forever

### ISSUE THREAD

**Issue by b0bc4t** [hashcat/hashcat#1341]
Hi, 

we think we have found a bug in the handling of the cracking threads. In particular, hashcat is prevented from finishing its task about once every 20 runs when bypassed/cancelled. We are running with hashcat v3.5.0, which has a small extension that is most likely not relevant for the bug, because we experienced the same problem with the untouched hashcat version.

Below you can find our setup and a stacktrace of all running threads. It looks like the pthread_join() is not able to return once the current task has been bypassed/cancelled.

Let me know if you need further information.

Our system:
- Ubuntu 16.04.3
- 2x AMD Radeon R9 200 Series
- OpenCL 1.2 AMD-APP (2442.7)
- amdgpu-pro-17.30-458935
- Intel Core i5-4430 CPU @ 3.00GHz

```
Thread 9 (Thread 0x7f0567fff700 (LWP 2595)):
#0  0x00007f05eb8f7827 in futex_abstimed_wait_cancelable (private=0, abstime=0x0,
    expected=0, futex_word=0x7f056c004d58)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0x7f056c004d58, abstime=0x0)
    at sem_waitcommon.c:111
#2  0x00007f05eb8f78d4 in __new_sem_wait_slow (sem=0x7f056c004d58, abstime=0x0)
    at sem_waitcommon.c:181
#3  0x00007f05eb8f797a in __new_sem_wait (sem=<optimized out>) at sem_wait.c:29
#4  0x00007f05e2ed2260 in ?? ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
#5  0x00007f05e2ed00a6 in ?? ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
#6  0x00007f05e2ebcd68 in ?? ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
#7  0x00007f05e2e9f6b9 in clEnqueueWriteBuffer ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
#8  0x000000000048d833 in hc_clEnqueueWriteBuffer (hashcat_ctx=0x11d8010,
    command_queue=0x176c5f0, buffer=0x16ec9f0, blocking_write=1, offset=0,
    cb=9191424, ptr=0x7f048259d010, num_events_in_wait_list=0, event_wait_list=0x0,
    event=0x0) at src/opencl.c:589
#9  0x0000000000490e8c in run_copy (hashcat_ctx=0x11d8010,
    device_param=0x7f05e7eb0438, pws_cnt=33792) at src/opencl.c:1798
#10 0x000000000041a6cb in calc (hashcat_ctx=0x11d8010, device_param=0x7f05e7eb0438)
    at src/dispatch.c:579
#11 0x000000000041a970 in thread_calc (p=0x1776e60) at src/dispatch.c:695
#12 0x00007f05eb8ef6ba in start_thread (arg=0x7f0567fff700) at pthread_create.c:333
#13 0x00007f05eb4213dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 8 (Thread 0x7f05677fe700 (LWP 2594)):
#0  0x00007f05eb8f7827 in futex_abstimed_wait_cancelable (private=0, abstime=0x0,
    expected=0, futex_word=0x7f0560003808)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0x7f0560003808, abstime=0x0)
    at sem_waitcommon.c:111
#2  0x00007f05eb8f78d4 in __new_sem_wait_slow (sem=0x7f0560003808, abstime=0x0)
    at sem_waitcommon.c:181
#3  0x00007f05eb8f797a in __new_sem_wait (sem=<optimized out>) at sem_wait.c:29
#4  0x00007f05e2ed2260 in ?? ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
#5  0x00007f05e2ed00a6 in ?? ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
#6  0x00007f05e2ebcd68 in ?? ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
#7  0x00007f05e2e9f6b9 in clEnqueueWriteBuffer ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
#8  0x000000000048d833 in hc_clEnqueueWriteBuffer (hashcat_ctx=0x11d8010,
    command_queue=0x12a4b70, buffer=0x13fad10, blocking_write=1, offset=0,
    cb=12255232, ptr=0x7f05767e3010, num_events_in_wait_list=0,
    event_wait_list=0x0, event=0x0) at src/opencl.c:589
#9  0x0000000000490e8c in run_copy (hashcat_ctx=0x11d8010,
    device_param=0x7f05e7e4c010, pws_cnt=45056) at src/opencl.c:1798
#10 0x000000000041a6cb in calc (hashcat_ctx=0x11d8010, device_param=0x7f05e7e4c010)
    at src/dispatch.c:579
#11 0x000000000041a970 in thread_calc (p=0x1776e50) at src/dispatch.c:695
#12 0x00007f05eb8ef6ba in start_thread (arg=0x7f05677fe700) at pthread_create.c:333
#13 0x00007f05eb4213dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 7 (Thread 0x7f05756dc700 (LWP 2591)):
#0  0x00007f05eb3e630d in nanosleep () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007f05eb3e625a in __sleep (seconds=0) at ../sysdeps/posix/sleep.c:55
#2  0x00000000004b4202 in hc_sleep (sec=1) at src/shared.c:190
#3  0x000000000049c96e in outfile_remove (hashcat_ctx=0x11d8010)
    at src/outfile_check.c:62
#4  0x000000000049d4b7 in thread_outfile_remove (p=0x11d8010)
    at src/outfile_check.c:299
#5  0x00007f05eb8ef6ba in start_thread (arg=0x7f05756dc700) at pthread_create.c:333
#6  0x00007f05eb4213dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 6 (Thread 0x7f0574edb700 (LWP 2590)):
#0  0x00007f05eb3e630d in nanosleep () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007f05eb3e625a in __sleep (seconds=0) at ../sysdeps/posix/sleep.c:55
#2  0x00000000004b4202 in hc_sleep (sec=1) at src/shared.c:190
#3  0x00000000004861c2 in monitor (hashcat_ctx=0x11d8010) at src/monitor.c:132
#4  0x0000000000486de3 in thread_monitor (p=0x11d8010) at src/monitor.c:422
#5  0x00007f05eb8ef6ba in start_thread (arg=0x7f0574edb700) at pthread_create.c:333
#6  0x00007f05eb4213dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 5 (Thread 0x7f05b0533700 (LWP 2587)):
#0  0x00007f05eb416f07 in ioctl () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007f05e265d9be in drmIoctl ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libdrm.so.2
#2  0x00007f05e2451e26 in ?? ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libdrm_amdgpu.so.1
#3  0x00007f05e2451f54 in amdgpu_cs_query_fence_status ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libdrm_amdgpu.so.1
#4  0x00007f05e32ccd10 in ?? ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
#5  0x00007f05e32a5b56 in ?? ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
#6  0x00007f05e32a5bb1 in ?? ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
#7  0x00007f05e2f31047 in ?? ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
#8  0x00007f05e2f313c3 in ?? ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
#9  0x00007f05e32e60c7 in ?? ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
#10 0x00007f05e32e6f49 in ?? ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
#11 0x00007f05e2f11a53 in ?? ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
#12 0x00007f05e2f06de8 in ?? ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
#13 0x00007f05e2f070a7 in ?? ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
#14 0x00007f05e2ef589c in ?? ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
#15 0x00007f05e2ef63b1 in ?? ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
#16 0x00007f05e2ec4258 in ?? ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
#17 0x00007f05e2ec5127 in ?? ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
#18 0x00007f05e2ecc4eb in ?? ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
#19 0x00007f05e2f0b199 in ?? ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
#20 0x00007f05e2f0b91a in ?? ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
#21 0x00007f05e2f0b9ba in ?? ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
#22 0x00007f05e2f0cdd7 in ?? ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
#23 0x00007f05e2f0d2f6 in ?? ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
#24 0x00007f05e2ebf026 in ?? ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
#25 0x00007f05e2ebf6cd in ?? ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
#26 0x00007f05e2e52fbf in ?? ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
#27 0x00007f05e2ed06ac in ?? ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
#28 0x00007f05eb8ef6ba in start_thread (arg=0x7f05b0533700) at pthread_create.c:333
#29 0x00007f05eb4213dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 4 (Thread 0x7f05b1b6c700 (LWP 2586)):
#0  0x00007f05eb416f07 in ioctl () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007f05e265d9be in drmIoctl ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libdrm.so.2
#2  0x00007f05e2451e26 in ?? ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libdrm_amdgpu.so.1
#3  0x00007f05e2451f54 in amdgpu_cs_query_fence_status ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libdrm_amdgpu.so.1
#4  0x00007f05e32ccd10 in ?? ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
#5  0x00007f05e32a5b56 in ?? ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
#6  0x00007f05e32a5bb1 in ?? ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
#7  0x00007f05e2f31047 in ?? ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
#8  0x00007f05e2f313c3 in ?? ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
#9  0x00007f05e32e60c7 in ?? ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
#10 0x00007f05e32e6f49 in ?? ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
#11 0x00007f05e2f11a53 in ?? ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
#12 0x00007f05e2f06de8 in ?? ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
#13 0x00007f05e2f070a7 in ?? ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
#14 0x00007f05e2ef589c in ?? ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
#15 0x00007f05e2ef63b1 in ?? ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
#16 0x00007f05e2ec4258 in ?? ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
#17 0x00007f05e2ec5127 in ?? ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
#18 0x00007f05e2ecc4eb in ?? ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
#19 0x00007f05e2f0b199 in ?? ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
#20 0x00007f05e2f0b91a in ?? ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
#21 0x00007f05e2f0b9ba in ?? ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
#22 0x00007f05e2f0cdd7 in ?? ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
#23 0x00007f05e2f0d2f6 in ?? ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
#24 0x00007f05e2ebf026 in ?? ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
#25 0x00007f05e2ebf6cd in ?? ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
#26 0x00007f05e2e52fbf in ?? ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
#27 0x00007f05e2ed06ac in ?? ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
#28 0x00007f05eb8ef6ba in start_thread (arg=0x7f05b1b6c700) at pthread_create.c:333
#29 0x00007f05eb4213dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 3 (Thread 0x7f05df0b8700 (LWP 2585)):
#0  0x00007f05eb417593 in select () at ../sysdeps/unix/syscall-template.S:84
#1  0x00000000004bb31a in tty_getchar () at src/terminal.c:340
#2  0x00000000004bae03 in keypress (hashcat_ctx=0x11d8010) at src/terminal.c:152
#3  0x00000000004bb13d in thread_keypress (p=0x11d8010) at src/terminal.c:276
#4  0x00007f05eb8ef6ba in start_thread (arg=0x7f05df0b8700) at pthread_create.c:333
#5  0x00007f05eb4213dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 2 (Thread 0x7f05df8b9700 (LWP 2584)):
#0  0x00007f05eb417593 in select () at ../sysdeps/unix/syscall-template.S:84
#1  0x000000000048b81b in network_loop (hashcat_ctx=0x11d8010)
    at src/network_control.c:72
#2  0x000000000048b9ee in thread_netcontrol (p=0x11d8010)
    at src/network_control.c:116
#3  0x00007f05eb8ef6ba in start_thread (arg=0x7f05df8b9700) at pthread_create.c:333
#4  0x00007f05eb4213dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 1 (Thread 0x7f05ebd1c700 (LWP 2581)):
#0  0x00007f05eb8f098d in pthread_join (threadid=139661187999488, thread_return=0x0)
    at pthread_join.c:90
#1  0x0000000000422ebd in inner2_loop (hashcat_ctx=0x11d8010) at src/hashcat.c:246
#2  0x00000000004232dc in inner1_loop (hashcat_ctx=0x11d8010) at src/hashcat.c:369
#3  0x0000000000423ebe in outer_loop (hashcat_ctx=0x11d8010) at src/hashcat.c:808
#4  0x00000000004249a9 in hashcat_session_execute (hashcat_ctx=0x11d8010)
    at src/hashcat.c:1187
#5  0x0000000000404c89 in main (argc=19, argv=0x7fff1b426198) at src/main.c:105
```

**Comment by jsteube** [comment]
As you can see in your backtrace, it's libamdocl64.so, so it's a amdgpu-pro problem. This doesn't really surprise as amdgpu-pro is full of OpenCL bugs.
