### ISSUE TITLE
Segmentation fault: 11 for specific set of rules & plains

### ISSUE THREAD

**Issue by mhasbini** [hashcat/hashcat#1359]
I'm at commit: 34c5eac5.

To reproduce the error:

`/tmp/rules`: http://termbin.com/1z7v
`/tmp/list`: http://termbin.com/jku7

```
$ ./hashcat --stdout -r /tmp/rules /tmp/list >/dev/null
Segmentation fault: 11

# with debug flags:
$ ./hashcat --stdout -r /tmp/rules /tmp/list >/dev/null
=================================================================
==60192==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x70000052c3b0 at pc 0x0001087c834e bp 0x70000052bee0 sp 0x70000052bed8
WRITE of size 1 at 0x70000052c3b0 thread T14
    #0 0x1087c834d in out_push stdout.c:41
    #1 0x1087c6846 in process_stdout stdout.c:141
    #2 0x1086f5c78 in choose_kernel opencl.c:1142
    #3 0x10870436b in run_cracker opencl.c:2272
    #4 0x1084d11d8 in calc dispatch.c:604
    #5 0x1084cea09 in thread_calc dispatch.c:705
    #6 0x7fff98c3699c in _pthread_body (libsystem_pthread.dylib+0x399c)
    #7 0x7fff98c36919 in _pthread_start (libsystem_pthread.dylib+0x3919)
    #8 0x7fff98c34350 in thread_start (libsystem_pthread.dylib+0x1350)

Address 0x70000052c3b0 is located in stack of thread T14 at offset 1072 in frame
    #0 0x1087c579f in process_stdout stdout.c:54

  This frame has 6 object(s):
    [32, 1072) 'out' <== Memory access at offset 1072 overflows this variable
    [1200, 1456) 'plain_buf'
    [1520, 1780) 'pw'
    [1856, 2116) 'pw67'
    [2192, 2452) 'pw147'
    [2528, 2788) 'pw188'
HINT: this may be a false positive if your program uses some custom stack unwind mechanism or swapcontext
      (longjmp and C++ exceptions *are* supported)
Thread T14 created by T0 here:
    #0 0x10890d379 in wrap_pthread_create (libclang_rt.asan_osx_dynamic.dylib+0x41379)
    #1 0x1084f9a49 in inner2_loop hashcat.c:247
    #2 0x1084f7e67 in inner1_loop hashcat.c:374
    #3 0x1084f55ec in outer_loop hashcat.c:829
    #4 0x1084f2133 in hashcat_session_execute hashcat.c:1197
    #5 0x10846c456 in main main.c:1087
    #6 0x7fff978295ac in start (libdyld.dylib+0x35ac)

SUMMARY: AddressSanitizer: stack-buffer-overflow stdout.c:41 in out_push
Shadow bytes around the buggy address:
  0x1e00000a5820: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1e00000a5830: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1e00000a5840: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1e00000a5850: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1e00000a5860: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x1e00000a5870: 00 00 00 00 00 00[f2]f2 f2 f2 f2 f2 f2 f2 f2 f2
  0x1e00000a5880: f2 f2 f2 f2 f2 f2 00 00 00 00 00 00 00 00 00 00
  0x1e00000a5890: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1e00000a58a0: 00 00 00 00 00 00 f2 f2 f2 f2 f2 f2 f2 f2 00 00
  0x1e00000a58b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1e00000a58c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 04 f2
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==60192==ABORTING
```

**Comment by jsteube** [comment]
Can not reproduce this locally:

```
root@ht:~/hashcat# md5sum rule
428fd5dc0934356ab2868661da01a653  rule
root@ht:~/hashcat# md5sum list 
1b569d308539fce2854cc1a117293122  list
root@ht:~/hashcat# ./hashcat --stdout -r rule list >/dev/null
root@ht:~/hashcat# 
```

How can I reproduce this?

**Comment by jsteube** [comment]
I've pushed a fix with https://github.com/hashcat/hashcat/commit/7a278ef035fd061291062814541b1e6812890809 that could in theory create an overflow because max password length is no longer 64 (so it's less than the subtract 100), but now its 256. Please retry on your system as I do not run into this error (on Linux BUFSIZ is 8k, while on OSX its 1k).

**Comment by mhasbini** [comment]
@jsteube I've applied 7a278ef and it seems to fix it 👍 

I'm on OSX, and I've noticed that the bug was dependent on the length of the plains and the order of applied rules.
