### ISSUE TITLE
segfault -m 2500 (WPA2) - AMD CPU

### ISSUE THREAD

**Issue by roycewilliams** [hashcat/hashcat#1556]
Also happening with 4.1.0 release. May be a local issue (driver?) but benchmark of -m 2500 does not fail. Currently only CPU drivers installed. This AMD OpenCL (1800.8) appears to be the latest available, but not sure. Note that benchmarks do not fail - only when actually trying a run. Does not happen when trying -m 0.

```
$./hashcat -I
hashcat (v4.1.0) starting...

OpenCL Info:

Platform ID #1
  Vendor  : Advanced Micro Devices, Inc.
  Name    : AMD Accelerated Parallel Processing
  Version : OpenCL 2.0 AMD-APP (1800.8)

  Device ID #1
    Type           : CPU
    Vendor ID      : 1
    Vendor         : AuthenticAMD
    Name           : AMD FX(tm)-8350 Eight-Core Processor
    Version        : OpenCL 1.2 AMD-APP (1800.8)
    Processor(s)   : 8
    Clock          : 1400
    Memory         : 8034/32139 MB allocatable
    OpenCL Version : OpenCL C 1.2
    Driver Version : 1800.8 (sse2,avx,fma4)

$ uname -rp
4.4.0-119-generic x86_64

$ rm -R ./kernels/

$ ./hashcat --version
v4.1.0-7-gf6cfcbbc+

$ cat test.list
password
testtest
Password1234

$ ./hashcat hashcat.hccapx test.list -m 2500
hashcat (v4.1.0-7-gf6cfcbbc+) starting...

OpenCL Platform #1: Advanced Micro Devices, Inc.
================================================
* Device #1: AMD FX(tm)-8350 Eight-Core Processor, 8034/32139 MB allocatable, 8MCU

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Applicable optimizers:
* Zero-Byte
* Single-Hash
* Single-Salt
* Slow-Hash-SIMD-LOOP

Minimum password length supported by kernel: 8
Maximum password length supported by kernel: 63

Watchdog: Hardware monitoring interface not found on your system.
Watchdog: Temperature abort trigger disabled.

Initializing device kernels and memory...Segmentation fault
```

It fails right around here:

```
[pid 11962] unlink("/home/royce/htp.troy/crackers/2/OpenCL/OCLzfcMUC.log") = 0
[pid 11962] unlink("/home/royce/htp.troy/crackers/2/OpenCL/OCLzfcMUC.cl") = 0
[pid 11962] statfs(".", {f_type="EXT2_SUPER_MAGIC", f_bsize=4096, f_blocks=53616686, f_bfree=4603474, f_bavail=1874131, f_files=13631488, f_ffree=12795570, f_fsid={1596389300, 1947951981}, f_namelen=255, f_frsize=4096, f_flags=3104}) = 0
[pid 11962] lseek(2, 0, SEEK_CUR)       = -1 ESPIPE (Illegal seek)
[pid 11962] lseek(2, 0, SEEK_CUR)       = -1 ESPIPE (Illegal seek)
[pid 11962] lseek(2, 0, SEEK_CUR)       = -1 ESPIPE (Illegal seek)
[pid 11962] lseek(2, 0, SEEK_CUR)       = -1 ESPIPE (Illegal seek)
[...]
[pid 11962] lseek(2, 0, SEEK_CUR)       = -1 ESPIPE (Illegal seek)
pid 12191] <... nanosleep resumed> NULL) = 0
[pid 12191] nanosleep({0, 100000000},  <unfinished ...>
[pid 12189] --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x38} ---
[pid 12200] +++ killed by SIGSEGV +++
[pid 12199] +++ killed by SIGSEGV +++
[pid 12198] +++ killed by SIGSEGV +++
[pid 12197] +++ killed by SIGSEGV +++
[pid 12196] +++ killed by SIGSEGV +++
[pid 12195] +++ killed by SIGSEGV +++
[pid 12194] +++ killed by SIGSEGV +++
[pid 12193] +++ killed by SIGSEGV +++
[pid 12192] +++ killed by SIGSEGV +++
[pid 12191] +++ killed by SIGSEGV +++
+++ killed by SIGSEGV +++
Segmentation fault

```
DEBUG=1

```
Initializing device kernels and memory...[New Thread 0x7ffff7fcc700 (LWP 12459)]
[New Thread 0x7fffbffff700 (LWP 12460)]
[New Thread 0x7fffbefea700 (LWP 12461)]
[New Thread 0x7fffbdfd5700 (LWP 12462)]
[New Thread 0x7fffaffff700 (LWP 12463)]
[New Thread 0x7fffaefea700 (LWP 12464)]
[New Thread 0x7fffadfd5700 (LWP 12465)]
[New Thread 0x7fff9ffff700 (LWP 12466)]
[New Thread 0x7fff9efea700 (LWP 12467)]
* Device #1: build_opts '-cl-std=CL1.2 -I OpenCL -I /usr/local/src/sec/crack/hashcat/github/hashcat/OpenCL -D VENDOR_ID=1 -D CUDA_ARCH=0 -D AMD_ROCM=0 -D VECT_SIZE=4 -D DEVICE_TYPE=2 -D DGST_R0=0 -D DGST_R1=1 -D DGST_R2=2 -D DGST_R3=3 -D DGST_ELEM=4 -D KERN_TYPE=2500 -D _unroll'
* Device #1: Kernel m02500.f7f71a8b.kernel not found in cache! Building may take a while...
"/usr/local/src/sec/crack/hashcat/github/hashcat/OpenCL/inc_common.cl", line 515: warning:
          variable "offset_minus_4" was declared but never referenced
    const int offset_minus_4 = 4 - offset_mod_4;
              ^

"/usr/local/src/sec/crack/hashcat/github/hashcat/OpenCL/inc_common.cl", line 1218: warning:
          variable "offset_minus_4" was declared but never referenced
    const int offset_minus_4 = 4 - offset_mod_4;
              ^

"/usr/local/src/sec/crack/hashcat/github/hashcat/OpenCL/inc_common.cl", line 4139: warning:
          variable "offset_minus_4" was declared but never referenced
    const int offset_minus_4 = 4 - offset_mod_4;
              ^

"/usr/local/src/sec/crack/hashcat/github/hashcat/OpenCL/inc_common.cl", line 11657: warning:
          variable "offset_minus_4" was declared but never referenced
    const int offset_minus_4 = 4 - offset_mod_4;
              ^

"/usr/local/src/sec/crack/hashcat/github/hashcat/OpenCL/inc_common.cl", line 31207: warning:
          variable "offset_minus_4" was declared but never referenced
    const int offset_minus_4 = 4 - offset_mod_4;
              ^

"/usr/local/src/sec/crack/hashcat/github/hashcat/OpenCL/inc_common.cl", line 31909: warning:
          variable "offset_minus_4" was declared but never referenced
    const int offset_minus_4 = 4 - offset_mod_4;
              ^

"/usr/local/src/sec/crack/hashcat/github/hashcat/OpenCL/inc_common.cl", line 34827: warning:
          variable "offset_minus_4" was declared but never referenced
    const int offset_minus_4 = 4 - offset_mod_4;
              ^

"/usr/local/src/sec/crack/hashcat/github/hashcat/OpenCL/inc_common.cl", line 42345: warning:
          variable "offset_minus_4" was declared but never referenced
    const int offset_minus_4 = 4 - offset_mod_4;
              ^

"/usr/local/src/sec/crack/hashcat/github/hashcat/OpenCL/inc_cipher_aes.cl", line 926: warning:
          variable "i" was declared but never referenced
    int i;
        ^

"/usr/local/src/sec/crack/hashcat/github/hashcat/OpenCL/inc_cipher_aes.cl", line 927: warning:
          variable "j" was declared but never referenced
    int j;
        ^

"/usr/local/src/sec/crack/hashcat/github/hashcat/OpenCL/OCLILkh0t.cl", line 749: warning:
          variable "s_td0" was declared but never referenced
    __constant u32a *s_td0 = td0;
                     ^

"/usr/local/src/sec/crack/hashcat/github/hashcat/OpenCL/OCLILkh0t.cl", line 750: warning:
          variable "s_td1" was declared but never referenced
    __constant u32a *s_td1 = td1;
                     ^

"/usr/local/src/sec/crack/hashcat/github/hashcat/OpenCL/OCLILkh0t.cl", line 751: warning:
          variable "s_td2" was declared but never referenced
    __constant u32a *s_td2 = td2;
                     ^

"/usr/local/src/sec/crack/hashcat/github/hashcat/OpenCL/OCLILkh0t.cl", line 752: warning:
          variable "s_td3" was declared but never referenced
    __constant u32a *s_td3 = td3;
                     ^

"/usr/local/src/sec/crack/hashcat/github/hashcat/OpenCL/OCLILkh0t.cl", line 753: warning:
          variable "s_td4" was declared but never referenced
    __constant u32a *s_td4 = td4;
                     ^


* Device #1: Kernel amp_a0.15818373.kernel not found in cache! Building may take a while...

Thread 1 "hashcat" received signal SIGSEGV, Segmentation fault.
0x00007fffe9528a8c in ?? () from /opt/AMDAPPSDK-3.0/lib/x86_64/libamdocl12cl64.so

(gdb) bt full
#0  0x00007fffe9528a8c in ?? () from /opt/AMDAPPSDK-3.0/lib/x86_64/libamdocl12cl64.so
No symbol table info available.
#1  0x00007fffe952908f in ?? () from /opt/AMDAPPSDK-3.0/lib/x86_64/libamdocl12cl64.so
No symbol table info available.
#2  0x00007fffe94823a5 in ?? () from /opt/AMDAPPSDK-3.0/lib/x86_64/libamdocl12cl64.so
No symbol table info available.
#3  0x00007fffe94925a7 in ?? () from /opt/AMDAPPSDK-3.0/lib/x86_64/libamdocl12cl64.so
No symbol table info available.
#4  0x00007fffe94adead in ?? () from /opt/AMDAPPSDK-3.0/lib/x86_64/libamdocl12cl64.so
No symbol table info available.
#5  0x00007fffe94b036d in ?? () from /opt/AMDAPPSDK-3.0/lib/x86_64/libamdocl12cl64.so
No symbol table info available.
#6  0x00007fffe9536d95 in ?? () from /opt/AMDAPPSDK-3.0/lib/x86_64/libamdocl12cl64.so
No symbol table info available.
#7  0x00007fffe9539037 in ?? () from /opt/AMDAPPSDK-3.0/lib/x86_64/libamdocl12cl64.so
No symbol table info available.
#8  0x00007fffe9539b23 in ?? () from /opt/AMDAPPSDK-3.0/lib/x86_64/libamdocl12cl64.so
No symbol table info available.
#9  0x00007fffe9c9278f in ?? () from /opt/AMDAPPSDK-3.0/lib/x86_64/libamdocl12cl64.so
No symbol table info available.
#10 0x00007fffe9c92b83 in ?? () from /opt/AMDAPPSDK-3.0/lib/x86_64/libamdocl12cl64.so
No symbol table info available.
#11 0x00007fffe9c92e3f in ?? () from /opt/AMDAPPSDK-3.0/lib/x86_64/libamdocl12cl64.so
No symbol table info available.
#12 0x00007fffe9c92f7c in ?? () from /opt/AMDAPPSDK-3.0/lib/x86_64/libamdocl12cl64.so
No symbol table info available.
#13 0x00007fffe968d9ec in ?? () from /opt/AMDAPPSDK-3.0/lib/x86_64/libamdocl12cl64.so
No symbol table info available.
#14 0x00007fffe968dc2c in ?? () from /opt/AMDAPPSDK-3.0/lib/x86_64/libamdocl12cl64.so
No symbol table info available.
#15 0x00007fffe8da7d06 in ?? () from /opt/AMDAPPSDK-3.0/lib/x86_64/libamdocl12cl64.so
No symbol table info available.
#16 0x00007fffe8da83d7 in ?? () from /opt/AMDAPPSDK-3.0/lib/x86_64/libamdocl12cl64.so
No symbol table info available.
#17 0x00007fffe8da8db0 in ?? () from /opt/AMDAPPSDK-3.0/lib/x86_64/libamdocl12cl64.so
No symbol table info available.
#18 0x00007fffe8db560a in ?? () from /opt/AMDAPPSDK-3.0/lib/x86_64/libamdocl12cl64.so
No symbol table info available.
#19 0x00007fffe8db771c in ?? () from /opt/AMDAPPSDK-3.0/lib/x86_64/libamdocl12cl64.so
No symbol table info available.
#20 0x00007fffebb37789 in aclCompile () from /opt/AMDAPPSDK-3.0/lib/x86_64/libamdocl64.so
No symbol table info available.
#21 0x00007fffeb227af0 in ?? () from /opt/AMDAPPSDK-3.0/lib/x86_64/libamdocl64.so
No symbol table info available.
#22 0x00007fffeb22828a in ?? () from /opt/AMDAPPSDK-3.0/lib/x86_64/libamdocl64.so
No symbol table info available.
#23 0x00007fffeb207eff in ?? () from /opt/AMDAPPSDK-3.0/lib/x86_64/libamdocl64.so
No symbol table info available.
#24 0x00007fffeb217ff0 in ?? () from /opt/AMDAPPSDK-3.0/lib/x86_64/libamdocl64.so
No symbol table info available.
#25 0x00007fffeb1f9130 in clBuildProgram () from /opt/AMDAPPSDK-3.0/lib/x86_64/libamdocl64.so
No symbol table info available.
#26 0x000000000045a69b in hc_clBuildProgram (hashcat_ctx=hashcat_ctx@entry=0x6c0010, program=<optimized out>, num_devices=num_devices@entry=1, device_list=device_list@entry=0x7fffeeded010,
    options=options@entry=0x7fffffffd380 "-cl-std=CL1.2 -I OpenCL -I /usr/local/src/sec/crack/hashcat/github/hashcat/OpenCL -D VENDOR_ID=1 -D CUDA_ARCH=0 -D AMD_ROCM=0 -D VECT_SIZE=4 -D DEVICE_TYPE=2 -D DGST_R0=0 -D DGST_R1=1 -D DGST_R2=2 -D "..., pfn_notify=pfn_notify@entry=0x0, user_data=0x0) at src/opencl.c:879
        opencl_ctx = <optimized out>
        ocl = <optimized out>
        CL_err = <optimized out>
#27 0x00000000004618c6 in opencl_session_begin (hashcat_ctx=hashcat_ctx@entry=0x6c0010) at src/opencl.c:5012
        rc_read_kernel = <optimized out>
        build_log_size = 3237
        binary_size = 7937088
        binary = 0xa33bd80 "\220\207\353\b"
        cached_file = "/usr/local/src/sec/crack/hashcat/github/hashcat/kernels/amp_a0.15818373.kernel", '\000' <repeats 177 times>
        cached = false
        kernel_sources_buf = 0x1d79b70 "/**\n * Author......: See docs/credits.txt\n * License.....: MIT\n */\n\n#include \"inc_hash_constants.h\"\n#include \"inc_vendor.cl\"\n#include \"inc_types.cl\"\n#include \"inc_rp.h\"\n#include \"inc_rp.cl\"\n\n__kernel "...
        kernel_sources = 0x7fffffffd0a0
---Type <return> to continue, or q <return> to quit---
        source_file = "/usr/local/src/sec/crack/hashcat/github/hashcat/OpenCL/amp_a0.cl", '\000' <repeats 191 times>
        kernel_lengths_buf = 685
        kernel_lengths = 0x7fffffffd098
        size_markov_css = 67371008
        size_shown = 4
        size_st_esalts = 608
        build_opts_new = "-cl-std=CL1.2 -I OpenCL -I /usr/local/src/sec/crack/hashcat/github/hashcat/OpenCL -D VENDOR_ID=1 -D CUDA_ARCH=0 -D AMD_ROCM=0 -D VECT_SIZE=4 -D DEVICE_TYPE=2 -D DGST_R0=0 -D DGST_R1=1 -D DGST_R2=2 -D "...
        kernel_accel_max = <optimized out>
        size_pws_amp = <optimized out>
        size_hooks = <optimized out>
        pws_idx = <optimized out>
        device_processors = 8
        size_st_digests = 16
        device_name_chksum_amp_mp = 0x8471e0 "15818373"
        kernel_name = "/usr/local/src/sec/crack/hashcat/github/hashcat/kernels/amp_a0.1"
        tuningdb_entry = <optimized out>
        size_rules_c = 32768
        device_name_chksum = 0x8461d0 "f7f71a8b"
        device_name_digest = {4160166539, 3317192757, 1060961911, 3984906652}
        size_salts = 564
        size_esalts = 608
        size_tm = 4096
        dnclen = <optimized out>
        size_pws_comp = <optimized out>
        combs_buf = <optimized out>
        size_results = 4
        size_plains = 32
        size_pws = <optimized out>
        size_tmps = <optimized out>
        pws_comp = <optimized out>
        hooks_buf = <optimized out>
        device_param = 0x7fffeeded010
        vector_width = 4
        size_digests = 16
        kernel_loops_fixed = <optimized out>
        size_combs = 266240
        size_bfs = 4096
        size_st_salts = 564
        dnclen_amp_mp = 103
        device_name_digest_amp_mp = {360809331, 3207344467, 259357148, 421125084}
        kernel_threads = <optimized out>
        properties = {4228, 140737194492976, 0}
        size_rules = 128
        scrypt_tmp_size = 0
        scrypt_tmto_final = <optimized out>
        size_pws_idx = <optimized out>
        size_scrypt = <optimized out>
        files_names = {0x49ca13 "inc_cipher_aes.cl", 0x49ca25 "inc_cipher_serpent.cl", 0x49ca3b "inc_cipher_twofish.cl", 0x49ca51 "inc_common.cl", 0x49ca5f "inc_comp_multi_bs.cl",
          0x49ca74 "inc_comp_multi.cl", 0x49ca86 "inc_comp_single_bs.cl", 0x49ca9c "inc_comp_single.cl", 0x49caaf "inc_hash_constants.h", 0x49cac4 "inc_hash_functions.cl",
          0x49cada "inc_rp_optimized.cl", 0x49caee "inc_rp_optimized.h", 0x49cb01 "inc_simd.cl", 0x49cb0d "inc_scalar.cl", 0x49cb1b "inc_types.cl", 0x49cb28 "inc_vendor.cl"}
        CL_rc = <optimized out>
        skipped_temp = <optimized out>
        kernel_accel_min = <optimized out>
        scratch_buf = <optimized out>
        size_root_css = 263168
        size_scrypt4 = 1
        build_opts = "-cl-std=CL1.2 -I OpenCL -I /usr/local/src/sec/crack/hashcat/github/hashcat/OpenCL -D VENDOR_ID=1 -D CUDA_ARCH=0 -D AMD_ROCM=0 -D VECT_SIZE=4 -D DEVICE_TYPE=2 -D DGST_R0=0 -D DGST_R1=1 -D DGST_R2=2 -D "...
        device_id = 0
        bitmap_ctx = <optimized out>
        folder_config = 0x6cb2d0
        hashconfig = <optimized out>
        hashes = 0x6cb3c0
        opencl_ctx = 0x6ce5f0
        straight_ctx = 0x6ce8a0
        user_options_extra = 0x6ce910
        user_options = <optimized out>
---Type <return> to continue, or q <return> to quit---
        hardware_power_all = 0
        has_skipped_temp = <optimized out>
#28 0x0000000000417fed in outer_loop (hashcat_ctx=hashcat_ctx@entry=0x6c0010) at src/hashcat.c:696
        hashes = 0x6cb3c0
        mask_ctx = 0x6cb540
        opencl_ctx = 0x6ce5f0
        outcheck_ctx = 0x6ce6a0
        restore_ctx = 0x6ce740
        status_ctx = 0x6ce770
        straight_ctx = 0x6ce8a0
        user_options = 0x6ce940
        rc_hashconfig = <optimized out>
        rc_hashes_init_stage1 = <optimized out>
        rc_hashes_init_stage2 = <optimized out>
        rc_hashes_init_stage3 = <optimized out>
        rc_hashes_init_stage4 = <optimized out>
        rc_hashes_init_selftest = <optimized out>
        rc_bitmap_init = <optimized out>
        rc_wl_data_init = <optimized out>
        rc_straight_init = <optimized out>
        rc_combinator_init = <optimized out>
        rc_mask_init = <optimized out>
        rc_status_init = <optimized out>
        rc_session_begin = <optimized out>
        threads_param = <optimized out>
        selftest_threads = <optimized out>
        rc_potfile_write = <optimized out>
        inner_threads_cnt = <optimized out>
        inner_threads = <optimized out>
#29 0x000000000041847d in hashcat_session_execute (hashcat_ctx=hashcat_ctx@entry=0x6c0010) at src/hashcat.c:1183
        logfile_ctx = 0x6cb4f0
        status_ctx = 0x6ce770
        user_options = 0x6ce940
        proc_start = 1523129605
        rc_final = -1
        proc_stop = <optimized out>
#30 0x0000000000403f9b in main (argc=5, argv=0x7fffffffdd78) at src/main.c:1060
        proc_start = 1523129605
        hashcat_ctx = 0x6c0010
        rc_hashcat_init = <optimized out>
        install_folder = 0x484009 "/usr/local/bin"
        shared_folder = 0x483ff0 "/usr/local/share/hashcat"
        rc_options_init = <optimized out>
        rc_options_getopt = <optimized out>
        rc_options_sanity = <optimized out>
        user_options = 0x6ce940
        rc_session_init = <optimized out>
        rc_final = -1
        proc_stop = <optimized out>

```

**Comment by jsteube** [comment]
This is pretty clear:

```
0x00007fffe9528a8c in ?? () from /opt/AMDAPPSDK-3.0/lib/x86_64/libamdocl12cl64.so
```

The segfault occurs inside the amd library. We can't do anything to workaround this type of error. It's not a hashcat error.

However, if you want to crack on CPU, please use the Intel OpenCL runtime (even for AMD CPU).
