### ISSUE TITLE
On raspberry pi running kali linux

### ISSUE THREAD

**Issue by StephensCG** [hashcat/hashcat#2247]
Traceback (most recent call last):
  File "./airscript-ng.py", line 30, in <module>
    import modules
  File "/root/Airscript-ng/modules/__init__.py", line 23, in <module>
    from .manage_deps import *
  File "/root/Airscript-ng/modules/manage_deps.py", line 23, in <module>
    from .gui_elements import pickYesOrNo
  File "/root/Airscript-ng/modules/gui_elements.py", line 24, in <module>
    Tk().withdraw() #Don't show the root window
  File "/usr/lib/python3.7/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

**Comment by philsmd** [comment]
wrong repository

this is the hashcat github repository (no python, no airscript-ng)

**Comment by StephensCG** [comment]
Thanks my mistake, now only if I could get hashcat to work, issue with make command
