### ISSUE TITLE
Some algorithms (like RAR3-p) not working in beta with ATI Vega64 GPU but on CPU

### ISSUE THREAD

**Issue by Sven1981** [hashcat/hashcat#2784]
I normally used the actual hashcat 6.1.1 stable. There are no problems, but some algorithms are not present, so i tried to use the beta. For example RAR3-p (23800) is only working on CPU, but not on GPU, there it just ends. Because I do not get any error message, I would be happy about any idea. Other algorithms work with the GPU without any problem.

CPU:  

```
C:\ProgramData\BOINC\projects\test>hashcat_beta.exe -m 23800 -D 1 -b
hashcat (v6.1.1-298-g95489b047) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

OpenCL API (OpenCL 2.1 AMD-APP (3224.5)) - Platform #1 [Advanced Micro Devices, Inc.]
=====================================================================================
* Device #1: gfx900, skipped

OpenCL API (OpenCL 2.1 WINDOWS) - Platform #2 [Intel(R) Corporation]
====================================================================
* Device #2: AMD Ryzen 5 3600X 6-Core Processor, 32613/32677 MB (8169 MB allocatable), 12MCU

Benchmark relevant options:
===========================
* --opencl-device-types=1
* --optimized-kernel-enable

Hashmode: 23800 - RAR3-p (Compressed) (Iterations: 262144)

Speed.#2.........:      864 H/s (54.82ms) @ Accel:64 Loops:16384 Thr:1 Vec:8

Started: Wed May 05 15:12:38 2021
Stopped: Wed May 05 15:12:43 2021
```

GPU:

```
C:\ProgramData\BOINC\projects\test>hashcat_beta.exe -m 23800 -D 2 -b
hashcat (v6.1.1-298-g95489b047) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

OpenCL API (OpenCL 2.1 AMD-APP (3224.5)) - Platform #1 [Advanced Micro Devices, Inc.]
=====================================================================================
* Device #1: gfx900, 8112/8176 MB (6732 MB allocatable), 56MCU

OpenCL API (OpenCL 2.1 WINDOWS) - Platform #2 [Intel(R) Corporation]
====================================================================
* Device #2: AMD Ryzen 5 3600X 6-Core Processor, skipped

Benchmark relevant options:
===========================
* --opencl-device-types=2
* --optimized-kernel-enable

Hashmode: 23800 - RAR3-p (Compressed) (Iterations: 262144)
```

**Comment by jsteube** [comment]
If there's no error message, then it crashed inside the driver. Keep in mind that AMD drivers are tested only on Linux. Is possible it's not working. If you switch to Linux make sure to use rocr driver for OpenCL. Maybe you have that option on the Windows drivers, too, I don't know.

**Comment by Sven1981** [comment]
> 
> 
> If there's no error message, then it crashed inside the driver. Keep in mind that AMD drivers are tested only on Linux. Is possible it's not working. If you switch to Linux make sure to use rocr driver for OpenCL. Maybe you have that option on the Windows drivers, too, I don't know.

Sounds logical, but it seemed strange to me, that other algorithms work with the same setup (hashcat beta, using GPU).

**Comment by ventaquil** [comment]
On my Ubuntu 20.04 it works okay (fresh Hashcat from `master` branch). Windows specific issue?

```
$ ./hashcat --hash-type 23800 --benchmark --optimized-kernel-enable
hashcat (v6.1.1-320-g9b7c2f8f5) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

OpenCL API (OpenCL 2.0 AMD-APP (3186.0)) - Platform #1 [Advanced Micro Devices, Inc.]
=====================================================================================
* Device #1: gfx900, 8064/8176 MB (6949 MB allocatable), 64MCU
* Device #2: gfx900, 8064/8176 MB (6949 MB allocatable), 64MCU
* Device #3: gfx900, 8064/8176 MB (6949 MB allocatable), 64MCU
* Device #4: gfx900, 8064/8176 MB (6949 MB allocatable), 64MCU

OpenCL API (OpenCL 2.1 LINUX) - Platform #2 [Intel(R) Corporation]
==================================================================
* Device #5: Intel(R) Xeon(R) Silver 4114 CPU @ 2.20GHz, skipped

Benchmark relevant options:
===========================
* --optimized-kernel-enable

Hashmode: 23800 - RAR3-p (Compressed) (Iterations: 262144)

Speed.#1.........:    47598 H/s (69.13ms) @ Accel:16 Loops:16384 Thr:64 Vec:1
Speed.#2.........:    52140 H/s (68.58ms) @ Accel:16 Loops:16384 Thr:64 Vec:1
Speed.#3.........:    47570 H/s (69.54ms) @ Accel:16 Loops:16384 Thr:64 Vec:1
Speed.#4.........:    47620 H/s (69.04ms) @ Accel:16 Loops:16384 Thr:64 Vec:1
Speed.#*.........:   194.9 kH/s

Started: Thu May  6 09:53:30 2021
Stopped: Thu May  6 09:53:48 2021
```

**Comment by jsteube** [comment]
It is an AMD driver problem, but only in the legacy driver. 

On Linux the user can select between the legacy (like in windows) and OSS driver rocm. The rocm is much faster and it seems more robust driver. On rocm, the problem will not occur (see paste from @ventaquil). 

To reproduce I have installed legacy driver on Linux to catch the segmentation fault with debugger and it clearly tells it's crashing inside the driver.

So this is not a hashcat issue, therefore closing the issue. Feel free to report it to AMD.

```
$ ./hashcat -b -m 23800 
hashcat (v6.1.1-328-gff72a8ed2+) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

OpenCL API (OpenCL 2.1 AMD-APP (3224.4)) - Platform #1 [Advanced Micro Devices, Inc.]
=====================================================================================
* Device #1: Ellesmere, 3968/4089 MB (3263 MB allocatable), 36MCU

OpenCL API (OpenCL 2.1 LINUX) - Platform #2 [Intel(R) Corporation]
==================================================================
* Device #2: AMD FX(tm)-6100 Six-Core Processor, skipped

Benchmark relevant options:
===========================
* --optimized-kernel-enable

Hashmode: 23800 - RAR3-p (Compressed) (Iterations: 262144)

Segmentation fault (core dumped)
```

```
$ gdb ./hashcat core
...
Reading symbols from ./hashcat...
[New LWP 33466]
[New LWP 33469]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./hashcat -b -m 23800'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fbe30de4b4c in ?? () from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl-orca64.so
[Current thread is 1 (Thread 0x7fbe41e41b80 (LWP 33466))]
(gdb) bt
#0  0x00007fbe30de4b4c in ?? () from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl-orca64.so
#1  0x00007fbe30df3dbf in ?? () from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl-orca64.so
#2  0x00007fbe312a2c0d in ?? () from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl-orca64.so
#3  0x00007fbe30cdc419 in ?? () from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl-orca64.so
#4  0x00007fbe30cdd36f in ?? () from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl-orca64.so
#5  0x00007fbe30cca28f in ?? () from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl-orca64.so
#6  0x00007fbe31595bc9 in ?? () from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl-orca64.so
#7  0x00007fbe31550e81 in ?? () from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl-orca64.so
#8  0x00007fbe31556093 in ?? () from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl-orca64.so
#9  0x00007fbe31522e72 in aclCompile () from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl-orca64.so
#10 0x00007fbe30c9418f in ?? () from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl-orca64.so
#11 0x00007fbe30a70be0 in ?? () from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl-orca64.so
#12 0x00007fbe30a73b47 in ?? () from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl-orca64.so
#13 0x00007fbe30a5a942 in ?? () from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl-orca64.so
#14 0x00007fbe30a36893 in clLinkProgram () from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl-orca64.so
#15 0x000055ca28c51910 in hc_clLinkProgram (hashcat_ctx=hashcat_ctx@entry=0x55ca2a5b02a0, context=<optimized out>, num_devices=num_devices@entry=1, device_list=device_list@entry=0x7fbe3561e8f8, options=options@entry=0x0, 
    num_input_programs=num_input_programs@entry=1, input_programs=0x7ffe3c652640, pfn_notify=0x0, user_data=0x0, program=0x7ffe3c6525a8) at src/backend.c:2603
#16 0x000055ca28c52ad0 in load_kernel (hashcat_ctx=hashcat_ctx@entry=0x55ca2a5b02a0, device_param=device_param@entry=0x7fbe35498010, kernel_name=kernel_name@entry=0x55ca28d03989 "main_kernel", 
    source_file=source_file@entry=0x7ffe3c652870 "/root/git/hashcat/OpenCL/m23800-optimized.cl", cached_file=cached_file@entry=0x7ffe3c652970 "/root/git/hashcat/kernels/m23800-optimized.271b7433.kernel", build_options_buf=<optimized out>, 
    build_options_buf@entry=0x55ca2b89db40 "-D KERNEL_STATIC -I OpenCL -I /root/git/hashcat/OpenCL -D LOCAL_MEM_TYPE=1 -D VENDOR_ID=1 -D CUDA_ARCH=0 -D HAS_ADD=0 -D HAS_ADDC=0 -D HAS_SUB=0 -D HAS_SUBC=0 -D HAS_VADD=0 -D HAS_VADDC=0 -D HAS_VADD_"..., 
    cache_disable=true, opencl_program=0x7fbe3561e910, cuda_module=0x7fbe3561e6c0) at src/backend.c:7844
#17 0x000055ca28c5cfe3 in backend_session_begin (hashcat_ctx=hashcat_ctx@entry=0x55ca2a5b02a0) at src/backend.c:8783
#18 0x000055ca28c0d0b9 in outer_loop (hashcat_ctx=hashcat_ctx@entry=0x55ca2a5b02a0) at src/hashcat.c:714
#19 0x000055ca28c0d625 in hashcat_session_execute (hashcat_ctx=0x55ca2a5b02a0) at src/hashcat.c:1187
#20 0x000055ca28c0adfe in main (argc=4, argv=0x7ffe3c652ca8) at src/main.c:1185
(gdb) 
```

See this line:

```
#0  0x00007fbe30de4b4c in ?? () from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl-orca64.so
```
