### ISSUE TITLE
--username causes segfault()

### ISSUE THREAD

**Issue by theobch** [hashcat/hashcat#996]
Hi @jsteube , hi all.

First of all, nice works on haschat, really impressive !

Now my problem:
after cracking some LM / NTLM hashes with 
~~~
root@kali:~/Desktop/hashcat# ./hashcat64.bin -a 3 -m 3000 -username -1 ?u?d?s --increment dump/file ?1?1?1?1?1?1?1?1 -o output_kali/lm_hash.txt
~~~
for LM hashes and with
~~~
root@kali:~/Desktop/hashcat# ./hashcat64.bin -a 0 -m 1000 -w 4 -d 1 --gpu-temp-disable --potfile-path=hashcat.potfile -r rules/best64_new.rule dump/file dictionnaries/* -o output_kali/ntlm_hash.txt
~~~
for NTLM hashes, I want to display them into two separates files, one for LM, one for NTLM.
So I use those commands, the first to display username + NTLM hashes + password into a specific file; the second to display username + LM hashes + password into an other file:
~~~
root@kali:~/Desktop/hashcat#  ./hashcat64.bin -m 1000 --username --potfile-path ./hashcat.potfile --show -o output_kali/ntlm_result.txt original/dump/file
~~~
and
~~~
root@kali:~/Desktop/hashcat# ./hashcat64.bin -m 3000 --username --potfile-path ./hashcat.potfile --show -o output_kali/lm_result.txt original/dump/file
~~~
Problem: last command segfault. If I entered the last one (to display user + LM hashes + password) __without__ `--username` flag, command execute well. But If I passed `--username` flag, boom; segfault.

Here dmesg log:
~~~
[ 1959.775051] hashcat64.bin[3774]: segfault at 0 ip 0000000000455b5d sp 00007ffddb9e1c50 error 6 in hashcat64.bin[400000+8f000]
[ 2307.617436] hashcat64.bin[3811]: segfault at 0 ip 0000000000455b5d sp 00007ffff3d48610 error 6 in hashcat64.bin[400000+8f000]
~~~
and gdb:
~~~
root@kali:~/Desktop/hashcat# gdb ./hashcat64.bin 
(gdb) run -m 3000 --username --potfile-path ./hashcat.potfile --show -o output_kali/lm.txt Servier2017/fulldump_201701_hashes.txt
Starting program: /root/Desktop/hashcat/hashcat64.bin -m 3000 --username --potfile-path ./hashcat.potfile --show -o output_kali/lm.txt Servier2017/fulldump_201701_hashes.txt
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x0000000000455b5d in ?? ()
(gdb) bt
#0  0x0000000000455b5d in ?? ()
#1  0x00000000004154a0 in ?? ()
#2  0x0000000000415972 in ?? ()
#3  0x0000000000402548 in ?? ()
#4  0x00007ffff763b2b1 in __libc_start_main (main=0x402420, argc=10, argv=0x7fffffffded8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdec8) at ../csu/libc-start.c:291
#5  0x0000000000402599 in ?? ()
(gdb) 
~~~

Am I doing something wrong ?
If it's important, I use a Dell Precision 7510, with
* RAM : 16Gb;
* GPU : Nvidia Quadro M2000M (PCIe/SSE2)
* CPU : i7 6920HQ

and Nvidia Driver 375.26.

**Comment by philsmd** [comment]
Thanks for the report. I was able to reproduce this problem with the following (minimalized) steps:

```
$ cat 1000_3000.hash 
Administrator:500:0000000000000000299bd128c1101fd6:b4b9b02e6f09a9bd760f388b67351e2b:::
$ cat dict.txt
hashcat
$ ./hashcat -m 3000 1000_3000.hash dict.txt
299bd128c1101fd6:HASHCAT
$ ./hashcat --username --show -m 3000 1000_3000.hash 
Segmentation fault (core dumped)
```

So what I understand from this is that it doesn't matter if you specify --potfile-path and it only happens if --username was specified (even if it wasn't necessary, because hashcat recognized the pwdump format).

We will investigate and hopefully fix this soon.
Thx
